---
title: "Forest Fires - Predictive Modelling"
output: html_notebook
---

# Predictive Modelling

```{r}
# Libraries
library(readr)
library(tidymodels)
library(tidyverse)

# Read file
fires <- read_csv('data/newFires2.csv')

fires %>% 
  count(intentional_cause) %>% 
  mutate(prop = n/sum(n))

# Split data into training(0.7) and testing(0.3)

fires_split <- fires %>% initial_split(prop=.7,strata=intentional_cause)
fires_train <- training(fires_split)
fires_test  <- testing(fires_split)

set.seed(123)
fires_folds <- vfold_cv(fires_train,v=10 ,repeats=1)

```

```{r}

#Creating Recipes

fires_rec <- recipe(intentional_cause ~ ., data=fires_train)  %>% 
  step_rm(id) %>% 
  step_rm(municipality) %>% 
  step_rm(parish) %>% 
  step_rm(lat) %>%
  step_rm(lon) %>% 
  step_rm(alert_hour) %>% 
  step_date(alert_date) %>% 
  step_date(extinction_date) %>% 
  step_date(firstInterv_date) %>% 
  step_naomit(everything(), skip = TRUE) %>% 
  step_novel(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric(), -all_outcomes()) %>%
  step_corr(all_numeric_predictors(), threshold = 0.7, method = "spearman") %>%
  step_bin2factor(all_outcomes())

summary(fires_rec)

fires_nodates_rec <- recipe(intentional_cause ~ ., data=fires_train)  %>% 
  step_rm(id) %>% 
  step_rm(municipality) %>% 
  step_rm(parish) %>% 
  step_rm(lat) %>%
  step_rm(lon) %>% 
  step_rm(alert_hour) %>% 
  step_rm(alert_date) %>% 
  step_rm(extinction_date) %>% 
  step_rm(firstInterv_date) %>% 
  step_naomit(everything(), skip = TRUE) %>% 
  step_novel(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric(), -all_outcomes()) %>%
  step_corr(all_numeric_predictors(), threshold = 0.7, method = "spearman") %>%
  step_bin2factor(all_outcomes())

```

## Logistic Regression

```{r}
# Workflow

lr_model <- logistic_reg(mode="classification",engine="glmnet", penalty = tune(), mixture=1)

lr_reg_grid <- tibble(penalty = 10^seq(-4, -1, length.out = 30))
lr_reg_grid %>% top_n(-5) # lowest penalty values
lr_reg_grid %>% top_n(5)  # highest penalty values


lr_wf <- workflow() %>%
  add_model(lr_model) %>%
  add_recipe(fires_nodates_rec)

lr_res <- 
  lr_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    grid = lr_reg_grid,
    metrics = metric_set(roc_auc),
    control = control_grid(save_pred = TRUE)
    )
lr_res %>%  collect_metrics(summarize = TRUE)
```
```{r}

lr_pred <- 
  lr_res %>%
  collect_predictions()

lr_pred %>% 
  group_by(penalty) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()

```

## CART

```{r}
cart_model <- decision_tree(mode="classification",engine="rpart", tree_depth = tune(), min_n = tune())
cart_wf <- workflow() %>%
  add_model(cart_model) %>%
  add_recipe(fires_rec)
cart_grid <- grid_regular(tree_depth(), min_n(), levels = c(tree_depth = 5, min_n = 2))
cart_res <- 
  cart_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    metrics = metric_set(roc_auc),
    grid = cart_grid,
    control = control_resamples(save_pred = TRUE)
    ) 
collect_metrics(cart_res)

```

```{r}
cart_pred <- 
  cart_res %>%
  collect_predictions()

cart_pred %>% 
  group_by(tree_depth) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()
```

## kNN

```{r}
knn_model <- nearest_neighbor(mode="classification",engine="kknn",
                              neighbors = tune(),
                              dist_power = tune()
                              )

knn_grid <- grid_regular(neighbors(), dist_power(), levels = c(neighbors = 10, dist_power = 2))

knn_wf <- workflow() %>%
  add_model(knn_model) %>%
  add_recipe(fires_rec)
knn_res <- 
  knn_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    grid = knn_grid,
    metrics = metric_set(roc_auc),
    control = control_resamples(save_pred = TRUE)
    ) 
collect_metrics(knn_res)

```

```{r}
knn_pred <- 
  knn_res %>%
  collect_predictions()

knn_pred %>% 
  group_by(neighbors) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()
```

## Neural Network

```{r}
# Workflow

nn_model <- mlp(mode="classification",engine="nnet", 
  hidden_units = tune(),
  penalty = tune(),
  epochs = 10)

nn_grid <- grid_regular(hidden_units(), penalty(), levels = c(hidden_units = 5, penalty = 5))

nn_wf <- workflow() %>%
  add_model(nn_model) %>%
  add_recipe(fires_nodates_rec)
nn_res <- 
  nn_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    metrics = metric_set(roc_auc),
    grid = nn_grid,
    control = control_resamples(save_pred = TRUE)
    )
nn_res %>%  collect_metrics(summarize = TRUE)
```

```{r}

nn_pred <- 
  nn_res %>%
  collect_predictions()

nn_pred %>% 
  group_by(id) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()

```

## Naive Bayes

```{r}
# Workflow
library(discrim)
library(klaR)

nb_model <- naive_Bayes(mode="classification",engine="klaR", 
  smoothness = tune(),
  Laplace = tune()
  )

nb_grid <- grid_regular(smoothness(), Laplace(), levels = c(smoothness = 5, Laplace = 5))

nb_wf <- workflow() %>%
  add_model(nb_model) %>%
  add_recipe(fires_nodates_rec)

nb_res <- 
  nb_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    metrics = metric_set(roc_auc),
    grid = nb_grid,
    control = control_resamples(save_pred = TRUE)
    )
nb_res %>%  collect_metrics(summarize = TRUE)
```

```{r}

nb_pred <- 
  nb_res %>%
  collect_predictions()

nb_pred %>% 
  group_by(id) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()

```

## Random Forest

```{r}
# Workflow

cores <- parallel::detectCores()

rf_model <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>% 
  set_engine("ranger", num.threads = cores) %>% 
  set_mode("classification")

#rf_grid <- grid_regular(mtry(), min_n(), levels = c(mtry = 5, min_n = 5))

rf_wf <- workflow() %>%
  add_model(rf_model) %>%
  add_recipe(fires_rec)

rf_res <- 
  rf_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    metrics = metric_set(roc_auc),
    grid = 25,
    control = control_resamples(save_pred = TRUE)
    )
rf_res %>%  collect_metrics(summarize = TRUE)
```

```{r}

rf_pred <- 
  rf_res %>%
  collect_predictions()

rf_pred %>% 
  group_by(id) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()

```

## Boosted Trees

```{r}
# Workflow

cores <- parallel::detectCores()

bt_model <- 
  boost_tree(mtry = tune(), min_n = tune(), trees = 100) %>% 
  set_engine("xgboost", num.threads = cores) %>% 
  set_mode("classification")

#bt_grid <- grid_regular(tree_depth(), min_n(), levels = c(tree_depth = 5, min_n = 5))

bt_wf <- workflow() %>%
  add_model(bt_model) %>%
  add_recipe(fires_nodates_rec)

bt_res <- 
  bt_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    metrics = metric_set(roc_auc),
    grid = 25,
    control = control_resamples(save_pred = TRUE)
    )
bt_res %>%  collect_metrics(summarize = TRUE)
```

```{r}

bt_pred <- 
  bt_res %>%
  collect_predictions()

bt_pred %>% 
  group_by(id) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()

```


## SVM

```{r}

# Workflow

cores <- parallel::detectCores()

svm_model <- 
  svm_poly(cost = tune(), degree = tune()) %>% 
  set_engine("kernlab", num.threads = cores) %>% 
  set_mode("classification")

#svm_grid <- grid_regular(cost(), levels = c(cost = 15))

svm_wf <- workflow() %>%
  add_model(svm_model) %>%
  add_recipe(fires_rec)

svm_res <- 
  svm_wf %>% 
  tune_grid(
    resamples = fires_folds, 
    metrics = metric_set(roc_auc),
    grid = 16,
    control = control_resamples(save_pred = TRUE)
    )
svm_res %>%  collect_metrics(summarize = TRUE)
```

```{r}

svm_pred <- 
  svm_res %>%
  collect_predictions()

svm_pred %>% 
  group_by(id) %>% # id contains our folds
  roc_curve(intentional_cause, .pred_yes) %>% 
  autoplot()

```

## Comparisson of all models

```{r}
lr_best <- 
  lr_res %>% 
  select_best(metric = "roc_auc")
cart_best <- 
  cart_res %>% 
  select_best(metric = "roc_auc")
knn_best <- 
  knn_res %>% 
  select_best(metric = "roc_auc")
nn_best <- 
  nn_res %>% 
  select_best(metric = "roc_auc")
nb_best <- 
  nb_res %>% 
  select_best(metric = "roc_auc")
rf_best <- 
  rf_res %>% 
  select_best(metric = "roc_auc")
bt_best <- 
  bt_res %>% 
  select_best(metric = "roc_auc")
#svm_best <- 
#  svm_res %>% 
#  select_best(metric = "roc_auc")
```

```{r}
lr_auc <- 
  lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_curve(intentional_cause, .pred_yes) %>% 
  mutate(model = "Logistic Regression")
cart_auc <- 
  cart_res %>% 
  collect_predictions(parameters = cart_best) %>% 
  roc_curve(intentional_cause, .pred_yes) %>% 
  mutate(model = "Decision Tree")
knn_auc <- 
  knn_res %>% 
  collect_predictions(parameters = knn_best) %>% 
  roc_curve(intentional_cause, .pred_yes) %>% 
  mutate(model = "k-Nearest Neighbor")
nn_auc <- 
  nn_res %>% 
  collect_predictions(parameters = nn_best) %>% 
  roc_curve(intentional_cause, .pred_yes) %>% 
  mutate(model = "Neural Network")
nb_auc <- 
  nb_res %>% 
  collect_predictions(parameters = nb_best) %>% 
  roc_curve(intentional_cause, .pred_yes) %>% 
  mutate(model = "Naive Bayes")
rf_auc <- 
  rf_res %>% 
  collect_predictions(parameters = rf_best) %>% 
  roc_curve(intentional_cause, .pred_yes) %>% 
  mutate(model = "Random Forest")
bt_auc <- 
  bt_res %>% 
  collect_predictions(parameters = bt_best) %>% 
  roc_curve(intentional_cause, .pred_yes) %>% 
  mutate(model = "Boosted Trees")
#svm_auc <- 
#  svm_res %>% 
#  collect_predictions(parameters = svm_best) %>% 
#  roc_curve(intentional_cause, .pred_yes) %>% 
#  mutate(model = "Suport Vector Machine")

```

```{r}
bind_rows(lr_auc, cart_auc, knn_auc, nn_auc, nb_auc, rf_auc, bt_auc) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, col = model)) + 
  geom_path(linewidth = 1.5, alpha = 0.8) +
  geom_abline(lty = 3) + 
  coord_equal() + 
  scale_color_viridis_d(option = "plasma", end = .6)
```

## Last Fit

```{r}
rf_best
```

```{r}
cores <- parallel::detectCores()

rf_model <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>% 
  set_engine("ranger", num.threads = cores) %>% 
  set_mode("classification")

#rf_grid <- grid_regular(mtry(), min_n(), levels = c(mtry = 5, min_n = 5))

rf_wf <- workflow() %>%
  add_model(rf_model) %>%
  add_recipe(fires_rec)
```


```{r}
# the last model
last_rf_model <- 
  rand_forest(mtry = 4, min_n = 20, trees = 100) %>% 
  set_engine("ranger", num.threads = cores, importance = "impurity") %>% 
  set_mode("classification")

# the last workflow
last_rf_wf <- 
  rf_wf %>% 
  update_model(last_rf_model)

# the last fit
set.seed(345)
last_rf_fit <- 
  last_rf_wf %>% 
  last_fit(fires_split)

last_rf_fit

last_rf_fit %>% 
  collect_metrics()
```

```{r}
library(vip)

last_rf_fit %>% 
  extract_fit_parsnip() %>% 
  vip(num_features = 20)

```
# Preparing the submision file

```{r}
# Libraries
library(readr)
library(tidymodels)
library(tidyverse)

# Read file
fires <- read_csv('data/fires_test.csv')
#str(fires)
#summary(fires)
#View(fires)

# View important information about possible and missing values
for (col in colnames(fires)) {
  print(col)
  #print(unique(fires[,col]))
  #print(which(is.na(fires[,col])))
  print(sum(is.na(fires[,col])))
}

# Remove 'alert_source' --> (NA's:10309)
fires <- select(fires, -(alert_source))

# Remove 'extinction_hour' --> Not necessary
fires <- select(fires, -(extinction_hour))

# Remove 'firstInterv_hour' --> Not necessary
fires <- select(fires, -(firstInterv_hour))

# Two Possible Values for district Viana do Castelo
fires$district[(fires$district=='Viana Do Castelo')] <- 'Viana do Castelo'

# Fill Missing Region values
fires$region[(fires$region=='-' & fires$district=='Aveiro')] <- 'Beira Litoral'
fires$region[(fires$region=='-' & fires$district=='Coimbra')] <- 'Beira Litoral'
fires$region[(fires$region=='-' & fires$district=='Leiria')] <- 'Beira Litoral'
fires$region[(fires$region=='-' & fires$district=='Viseu')] <- 'Beira Litoral'
fires$region[(fires$region=='-' & fires$district=='Castelo Branco')] <- 'Beira Interior'
fires$region[(fires$region=='-' & fires$district=='Guarda')] <- 'Beira Interior'
fires$region[(fires$region=='-' & fires$district=='Santarém')] <- 'Ribatejo e Oeste'
fires$region[(fires$region=='-' & fires$district=='Faro')] <- 'Algarve'
fires$region[(fires$region=='-' & fires$district=='Bragança')] <- 'Trás-os-Montes'
fires$region[(fires$region=='-' & fires$district=='Vila Real')] <- 'Trás-os-Montes'
fires$region[(fires$region=='-' & fires$district=='Viana do Castelo')] <- 'Entre Douro e Minho'
fires$region[(fires$region=='-' & fires$district=='Braga')] <- 'Entre Douro e Minho'
fires$region[(fires$region=='-' & fires$district=='Porto')] <- 'Entre Douro e Minho'
fires$region[(fires$region=='-' & fires$district=='Beja')] <- 'Alentejo'
fires$region[(fires$region=='-' & fires$district=='Évora')] <- 'Alentejo'
fires$region[(fires$region=='-' & fires$district=='Portalegre')] <- 'Alentejo'
fires$region[(fires$region=='-' & fires$district=='Lisboa')] <- 'Lisboa e Vale do Tejo'
fires$region[(fires$region=='-' & fires$district=='Setúbal')] <- 'Lisboa e Vale do Tejo'

fires$district[(is.na(fires$region))] #Setúbal
fires$region[is.na(fires$region)] <- 'Lisboa e Vale do Tejo'

#################################################################################################################################
# Corrigir erros nas coordenadas
# Substituir ',', por '.' em valores
fires$lat <- chartr(',', '.', fires$lat)
fires$lon <- chartr(',', '.', fires$lon)

#################################################################################################################################
# Valores de coordenadas todas na mesma forma
fires$lat <- chartr('º', ':', fires$lat)
fires$lat <- chartr("'", ':', fires$lat)
fires$lat <- gsub('::', '', fires$lat)

fires$lon <- chartr('º', ':', fires$lon)
fires$lon <- chartr("'", ':', fires$lon)
fires$lon <- gsub('::', '', fires$lon)

#################################################################################################################################
# Valores de coordenadas na forma DMS
fires$lat <- sub(':','º',fires$lat)
fires$lat <- sub(':',"'",fires$lat)
#fires$lat <- paste0(fires$lat, "''")

fires$lon <- sub(':','º',fires$lon)
fires$lon <- sub(':',"'",fires$lon)
#fires$lon <- paste0(fires$lon, "''")

#################################################################################################################################
# Valores de coordenadas de DMS para DD
# Criar nova coluna com horas da latitude
horasLat <- unlist(gregexpr("º", fires$lat)) 
fires$horasLat <- substring(fires$lat, first=1, last=horasLat - 1)
# Criar nova coluna com minutos da latitude
minLat <- unlist(gregexpr("'", fires$lat)) # retornar posição com aquele caracter
fires$minLat <- substring(fires$lat, first=horasLat + 1, last=minLat - 1)
# Criar nova coluna com segundos da latitude
segLat <- length(fires$lat)
fires$segLat <- substring(fires$lat, first=minLat + 1, last=segLat)

# mudar o tipo das colunas 18, 19 e 20 de character para integer
fires[c(18, 19, 20)] <- lapply(fires[c(18, 19, 20)], as.integer) 
typeof(fires$segLat)
# alterar lat para DD
for (i in 1:4416) {
  if(!is.na(fires[i, 18]) & !is.na(fires[i, 19]) & !is.na(fires[i, 20])){
    latValue <- fires[i, 18] + (fires$minLat[!is.na(fires[i, 19])]/60) + (fires[i, 20]/3600)
    # Converter de double para string
    fires[i, 6]<- toString(latValue)
  }
}

# Criar nova coluna com horas da longitude
horasLon <- unlist(gregexpr("º", fires$lon)) # retorna posição deste caracter
fires$horasLon <- substring(fires$lon, first=1, last=horasLon - 1)
# Criar nova coluna com minutos da latitude
minLon <- unlist(gregexpr("'", fires$lon)) # retornar posição com aquele caracter
fires$minLon <- substring(fires$lon, first=horasLon + 1, last=minLon - 1)
# Criar nova coluna com segundos da latitude
segLon <- length(fires$lon)
fires$segLon <- substring(fires$lon, first=minLon + 1, last=segLon)

# mudar o tipo das colunas 22, 23 e 24 de character para integer
fires[c(21, 22, 23)] <- lapply(fires[c(21, 22, 23)], as.integer) 
typeof(fires$segLon)
# alterar lat para DD
for (i in 1:4416) {
  if(!is.na(fires[i, 21]) & !is.na(fires[i, 22]) & !is.na(fires[i, 23])){
    lonValue <- (fires[i, 21] + (fires$minLat[!is.na(fires[i, 22])]/60) + (fires[i, 23]/3600))*(-1)
    # Converter de double para string
    fires[i, 7]<- toString(lonValue)
  }
  if(is.na(fires[i, 21]) | is.na(fires[i, 22]) | is.na(fires[i, 23])){
    val <- fires[i, 7]
    value <- as.double(val)
    value <- value*(-1)
    fires[i, 7] <- toString(value)
  }
}

# Retirar hora de 'alert_date' e 'firstInterv_date'
fires$alert_date <- substring(fires$alert_date, first=1, last=10)
fires$firstInterv_date <- substring(fires$firstInterv_date, first=1, last=10)

# Tratar missing values em 'firstInterv_date', passando-lhes os respetivos valores em 'alert_date'
fires$firstInterv_date[(is.na(fires$firstInterv_date))] <- fires$alert_date[(is.na(fires$firstInterv_date))]

# Preecher missing values em 'extinction_date'
fires$alert_date = as.Date(fires$alert_date)
fires$extinction_date = as.Date(fires$extinction_date)


fires$diff_in_days = abs(as.numeric(difftime(fires$alert_date, fires$extinction_date, units = "days"))) 
meanDifference <- mean(fires$diff_in_days, na.rm=TRUE)
# Como meanDifference = 0.08..., a diferença será de 0 dias.

# Atribuir a missing values de 'extinction_date' o valor de 'alert_date'+1
fires$extinction_date[is.na(fires$extinction_date)] <- fires$alert_date[is.na(fires$extinction_date)]

#Relative Values for Areas
fires$village_area <- fires$village_area/fires$total_area
fires$vegetation_area <- fires$vegetation_area/fires$total_area
fires$farming_area <- fires$farming_area/fires$total_area
fires$village_veget_area <- fires$village_veget_area/fires$total_area

fires$village_area[(is.na(fires$village_area))] <- 0
fires$vegetation_area[(is.na(fires$vegetation_area))] <- 0
fires$farming_area[(is.na(fires$farming_area))] <- 0
fires$village_veget_area[(is.na(fires$village_veget_area))] <- 0


#install.packages("remotes")
library(remotes)
#install_github("bczernecki/climate")
library(climate)

fires[c(9)] <- lapply(fires[c(9)], as.character)

columns= c("Id", "station_ID","Date","TemperatureCAvg","TemperatureCMax","TemperatureCMin", "WindkmhDir", "WindkmhGust", "WindkmhInt")
# pass this vector length to ncol parameter
# and nrow with 0
meteo = data.frame(matrix(nrow = 0, ncol = length(columns)))

# assign column names
colnames(meteo) = columns

# display
print(meteo)

# lon = -8.471944
# lat = 42.01361
# data ="2014-01-11"
lon = fires[2, 7]
lat = fires[2, 6]
data = fires[2, 9]
data <- toString(data)
id = fires[2, 1]

# get the nearest station
nearest_station <-nearest_stations_ogimet(country = "Portugal",
                                          date = Sys.Date(),
                                          add_map = FALSE,
                                          point = c(lon, lat),
                                          no_of_stations = 1
)

# scrap meteorological data from Ogimet regarding a period and a specific station
meteo_data <- meteo_ogimet(date=data,
                           interval="daily",station=nearest_station$wmo_id)

# add a row to students_df
meteo = rbind(meteo, data.frame("Id"=id, "station_ID"=meteo_data$station_ID, "Date"=meteo_data$Date, "TemperatureCAvg"=meteo_data$TemperatureCAvg,
                                "TemperatureCMax"=meteo_data$TemperatureCMax, "TemperatureCMin"=meteo_data$TemperatureCMin,
                                "WindkmhDir"=meteo_data$WindkmhDir, "WindkmhGust"=meteo_data$WindkmhGust, "WindkmhInt"=meteo_data$WindkmhInt))

for(i in 1:4416) {       
  # Specifying expression
  #print(fires[i, 7])
  lon = fires[i, 7]
  lat = fires[i, 6]
  data = fires[i, 9]
  data <- toString(data)
  id = fires[i, 1]
  # get the nearest station
  tryCatch(               
    # Specifying expression
    expr = {                     
      nearest_station <-nearest_stations_ogimet(country = "Portugal",
                                                date = Sys.Date(),
                                                add_map = FALSE,
                                                point = c(lon, lat),
                                                no_of_stations = 1
      )
      # scrap meteorological data from Ogimet regarding a period and a specific station
      meteo_data <- meteo_ogimet(date=data,
                                 interval="daily",station=nearest_station$wmo_id)
      # add a row to students_df
      meteo = rbind(meteo, data.frame("Id"=id, "station_ID"=meteo_data$station_ID, "Date"=meteo_data$Date, "TemperatureCAvg"=meteo_data$TemperatureCAvg,
                                      "TemperatureCMax"=meteo_data$TemperatureCMax, "TemperatureCMin"=meteo_data$TemperatureCMin, 
                                      "WindkmhDir"=meteo_data$WindkmhDir, "WindkmhGust"=meteo_data$WindkmhGust, "WindkmhInt"=meteo_data$WindkmhInt))
      rm(nearest_station)
      rm(meteo_data)
      print("Everything was fine.")
    },
    error = function(e){         
      print("There was an error message.")
    }
  )
}

################################################################################################################################
# Criar variáveis "temp" -> temperatura e "windVelocity"
# mudar o tipo da coluna 9 para character
fires[c(9)] <- lapply(fires[c(9)], as.character) 
fires$alert_date <- substring(fires$alert_date, first=1, 10)

library(readr)

write.csv(meteo, "data/meteo_test.csv", row.names = FALSE)



meteo <- read_csv("data/meteo_test.csv")

fires <- mutate(fires, temp = NA)
fires <- mutate(fires, tempMax = NA)
fires <- mutate(fires, windVelocity = NA)
fires <- mutate(fires, windGust = NA)

for (j in 1:2985) {
  i <- as.numeric(meteo[j, 1])
  i <- i - 10309
  fires[i, 25] <- meteo[j, 4] # temp
  fires[i, 26] <- meteo[j, 5] # tempMax
  fires[i, 27] <- meteo[j, 9] # windVelocity
  fires[i, 28] <- meteo[j, 8] # windGust
}


write.csv(fires, "data/newFires_test.csv", row.names = FALSE)

newFires <- read_csv("data/newFires_test.csv")

#################################################################################################################################
# 'temp'
# Preencher missing values pelas medias da temperatura media em cada regiao

mediaTempBeiraLitoral <- mean(newFires$temp[newFires$region=='Beira Litoral'], na.rm=TRUE)
mediaTempBeiraInterior <- mean(newFires$temp[newFires$region=='Beira Interior'], na.rm=TRUE)
mediaTempRibatejoOeste <- mean(newFires$temp[newFires$region=='Ribatejo e Oeste'], na.rm=TRUE)
mediaTempTrasOsMontes <- mean(newFires$temp[newFires$region=='Trás-os-Montes'], na.rm=TRUE)
mediaTempAlgarve <- mean(newFires$temp[newFires$region=='Algarve'], na.rm=TRUE)
mediaTempEntreDouroMinho <- mean(newFires$temp[newFires$region=='Entre Douro e Minho'], na.rm=TRUE)
mediaTempAlentejo <- mean(newFires$temp[newFires$region=='Alentejo'], na.rm=TRUE)
mediaTempNorte <- mean(newFires$temp[newFires$region=='Norte'], na.rm=TRUE)
mediaTempLisboaTejo <- mean(newFires$temp[newFires$region=='Lisboa e Vale do Tejo'], na.rm=TRUE)
mediaTempCentro <- mean(newFires$temp[newFires$region=='Centro'], na.rm=TRUE)

for(i in 1:4416) { 
  if(newFires[i, 2] == 'Beira Litoral' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempBeiraLitoral 
  }
  if(newFires[i, 2] == 'Beira Interior' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempBeiraInterior 
  }
  if(newFires[i, 2] == 'Ribatejo e Oeste' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempRibatejoOeste 
  }
  if(newFires[i, 2] == 'Trás-os-Montes' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempTrasOsMontes 
  }
  if(newFires[i, 2] == 'Algarve' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempAlgarve 
  }
  if(newFires[i, 2] == 'Entre Douro e Minho' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempEntreDouroMinho
  }
  if(newFires[i, 2] == 'Alentejo' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempAlentejo
  }
  if(newFires[i, 2] == 'Norte' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempNorte
  }
  if(newFires[i, 2] == 'Lisboa e Vale do Tejo' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempLisboaTejo
  }
  if(newFires[i, 2] == 'Centro' & is.na(newFires[i, 25])){
    newFires[i, 25] <- mediaTempCentro
  }
}

#################################################################################################################################
# 'windVelocity'
# Preencher missing values pelas medias da windVelocity em cada regiao
mediaWindBeiraLitoral <- mean(newFires$windVelocity[newFires$region=='Beira Litoral'], na.rm=TRUE)
mediaWindBeiraInterior <- mean(newFires$windVelocity[newFires$region=='Beira Interior'], na.rm=TRUE)
mediaWindRibatejoOeste <- mean(newFires$windVelocity[newFires$region=='Ribatejo e Oeste'], na.rm=TRUE)
mediaWindTrasOsMontes <- mean(newFires$windVelocity[newFires$region=='Trás-os-Montes'], na.rm=TRUE)
mediaWindAlgarve <- mean(newFires$windVelocity[newFires$region=='Algarve'], na.rm=TRUE)
mediaWindEntreDouroMinho <- mean(newFires$windVelocity[newFires$region=='Entre Douro e Minho'], na.rm=TRUE)
mediaWindAlentejo <- mean(newFires$windVelocity[newFires$region=='Alentejo'], na.rm=TRUE)
mediaWindNorte <- mean(newFires$windVelocity[newFires$region=='Norte'], na.rm=TRUE)
mediaWindLisboaTejo <- mean(newFires$windVelocity[newFires$region=='Lisboa e Vale do Tejo'], na.rm=TRUE)
mediaWindCentro <- mean(newFires$windVelocity[newFires$region=='Centro'], na.rm=TRUE)

for(i in 1:4416) { 
  if(newFires[i, 2] == 'Beira Litoral' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindBeiraLitoral 
  }
  if(newFires[i, 2] == 'Beira Interior' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindBeiraInterior 
  }
  if(newFires[i, 2] == 'Ribatejo e Oeste' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindRibatejoOeste 
  }
  if(newFires[i, 2] == 'Trás-os-Montes' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindTrasOsMontes 
  }
  if(newFires[i, 2] == 'Algarve' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindAlgarve 
  }
  if(newFires[i, 2] == 'Entre Douro e Minho' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindEntreDouroMinho
  }
  if(newFires[i, 2] == 'Alentejo' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindAlentejo
  }
  if(newFires[i, 2] == 'Norte' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindNorte
  }
  if(newFires[i, 2] == 'Lisboa e Vale do Tejo' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindLisboaTejo
  }
  if(newFires[i, 2] == 'Centro' & is.na(newFires[i, 27])){
    newFires[i, 27] <- mediaWindCentro
  }
}

#################################################################################################################################
# 'tempMax'
# Preencher missing values pelas medias da tempMax em cada regiao
mediaTempMaxBeiraLitoral <- mean(newFires$tempMax[newFires$region=='Beira Litoral'], na.rm=TRUE)
mediaTempMaxBeiraInterior <- mean(newFires$tempMax[newFires$region=='Beira Interior'], na.rm=TRUE)
mediaTempMaxRibatejoOeste <- mean(newFires$tempMax[newFires$region=='Ribatejo e Oeste'], na.rm=TRUE)
mediaTempMaxTrasOsMontes <- mean(newFires$tempMax[newFires$region=='Trás-os-Montes'], na.rm=TRUE)
mediaTempMaxAlgarve <- mean(newFires$tempMax[newFires$region=='Algarve'], na.rm=TRUE)
mediaTempMaxEntreDouroMinho <- mean(newFires$tempMax[newFires$region=='Entre Douro e Minho'], na.rm=TRUE)
mediaTempMaxAlentejo <- mean(newFires$tempMax[newFires$region=='Alentejo'], na.rm=TRUE)
mediaTempMaxNorte <- mean(newFires$tempMax[newFires$region=='Norte'], na.rm=TRUE)
mediaTempMaxLisboaTejo <- mean(newFires$tempMax[newFires$region=='Lisboa e Vale do Tejo'], na.rm=TRUE)
mediaTempMaxCentro <- mean(newFires$tempMax[newFires$region=='Centro'], na.rm=TRUE)

for(i in 1:4416) { 
  if(newFires[i, 2] == 'Beira Litoral' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxBeiraLitoral 
  }
  if(newFires[i, 2] == 'Beira Interior' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxBeiraInterior 
  }
  if(newFires[i, 2] == 'Ribatejo e Oeste' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxRibatejoOeste 
  }
  if(newFires[i, 2] == 'Trás-os-Montes' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxTrasOsMontes 
  }
  if(newFires[i, 2] == 'Algarve' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxAlgarve 
  }
  if(newFires[i, 2] == 'Entre Douro e Minho' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxEntreDouroMinho
  }
  if(newFires[i, 2] == 'Alentejo' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxAlentejo
  }
  if(newFires[i, 2] == 'Norte' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxNorte
  }
  if(newFires[i, 2] == 'Lisboa e Vale do Tejo' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxLisboaTejo
  }
  if(newFires[i, 2] == 'Centro' & is.na(newFires[i, 26])){
    newFires[i, 26] <- mediaTempMaxCentro
  }
}

#################################################################################################################################
# 'windGust'
# Preencher missing values pelas medias da windGust em cada regiao
mediaWindGustBeiraLitoral <- mean(newFires$windGust[newFires$region=='Beira Litoral'], na.rm=TRUE)
mediaWindGustBeiraInterior <- mean(newFires$windGust[newFires$region=='Beira Interior'], na.rm=TRUE)
mediaWindGustRibatejoOeste <- mean(newFires$windGust[newFires$region=='Ribatejo e Oeste'], na.rm=TRUE)
mediaWindGustTrasOsMontes <- mean(newFires$windGust[newFires$region=='Trás-os-Montes'], na.rm=TRUE)
mediaWindGustAlgarve <- mean(newFires$windGust[newFires$region=='Algarve'], na.rm=TRUE)
mediaWindGustEntreDouroMinho <- mean(newFires$windGust[newFires$region=='Entre Douro e Minho'], na.rm=TRUE)
mediaWindGustAlentejo <- mean(newFires$windGust[newFires$region=='Alentejo'], na.rm=TRUE)
mediaWindGustNorte <- mean(newFires$windGust[newFires$region=='Norte'], na.rm=TRUE)
mediaWindGustLisboaTejo <- mean(newFires$windGust[newFires$region=='Lisboa e Vale do Tejo'], na.rm=TRUE)
mediaWindGustCentro <- mean(newFires$windGust[newFires$region=='Centro'], na.rm=TRUE)

for(i in 1:4416) { 
  if(newFires[i, 2] == 'Beira Litoral' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustBeiraLitoral 
  }
  if(newFires[i, 2] == 'Beira Interior' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustBeiraInterior 
  }
  if(newFires[i, 2] == 'Ribatejo e Oeste' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustRibatejoOeste 
  }
  if(newFires[i, 2] == 'Trás-os-Montes' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustTrasOsMontes 
  }
  if(newFires[i, 2] == 'Algarve' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustAlgarve 
  }
  if(newFires[i, 2] == 'Entre Douro e Minho' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustEntreDouroMinho
  }
  if(newFires[i, 2] == 'Alentejo' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustAlentejo
  }
  if(newFires[i, 2] == 'Norte' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustNorte
  }
  if(newFires[i, 2] == 'Lisboa e Vale do Tejo' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustLisboaTejo
  }
  if(newFires[i, 2] == 'Centro' & is.na(newFires[i, 28])){
    newFires[i, 28] <- mediaWindGustCentro
  }
}

#################################################################################################################################
# Retirar a variável 'horasLat' --> Não é necessário
newFires <- select(newFires, -(horasLat))

# Retirar a variável 'minLat' --> Não é necessário
newFires <- select(newFires, -(minLat))

# Retirar a variável 'segLat' --> Não é necessário
newFires <- select(newFires, -(segLat))

# Retirar a variável 'horasLon' --> Não é necessário
newFires <- select(newFires, -(horasLon))

# Retirar a variável 'minLon' --> Não é necessário
newFires <- select(newFires, -(minLon))

# Retirar a variável 'segLon' --> Não é necessário
newFires <- select(newFires, -(segLon))

# Retirar a variável 'diff_in_days' --> Não é necessário
newFires <- select(newFires, -(diff_in_days))

fires$alert_date <- paste(fires$alert_date,fires$alert_hour,sep=" ")
fires$alert_date <- as.POSIXct(fires$alert_date)

write.csv(newFires, "data/newFires2_test.csv", row.names = FALSE)
```

## Predictions

```{r}
# Libraries
library(readr)
library(tidymodels)
library(tidyverse)

# Read file
fires <- read_csv('data/newFires2.csv')

# Split data into training(0.7) and testing(0.3)
set.seed(123)

fires_split <- fires %>% initial_split(prop=.7,strata=intentional_cause)
train <- training(fires_split)
test  <- testing(fires_split)

fires_rec <- recipe(intentional_cause ~., train)

fires_rec <- fires_rec %>% 
  step_rm(id) %>% 
  step_rm(municipality) %>% 
  step_rm(parish) %>% 
  step_rm(lat) %>%
  step_rm(lon) %>% 
  step_rm(alert_hour) %>% 
  step_date(alert_date) %>% 
  step_date(extinction_date) %>% 
  step_date(firstInterv_date) %>% 
  step_naomit(everything(), skip = TRUE) %>% 
  step_novel(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric(), -all_outcomes()) %>%
  step_corr(all_numeric_predictors(), threshold = 0.7, method = "spearman") %>%
  prep()

fires_final_test <- read_csv('data/newFires2_test.csv')

fires_train <- fires_rec %>% step_bin2factor(all_outcomes()) %>% prep() %>% bake(new_data=NULL)
fires_test <- fires_rec %>% bake(new_data=fires_final_test)

```

```{r}
cores <- parallel::detectCores()

model_rf <- 
  rand_forest(mtry = 4, min_n = 20, trees = 100) %>% 
  set_engine("ranger", num.threads = cores, importance = "impurity") %>% 
  set_mode("classification")

rf_fit <- model_rf %>%
  fit(intentional_cause ~ ., data=fires_train)


```

```{r}

preds <- predict(rf_fit, new_data = fires_test, type="prob")

preds

```

```{r}
submission <- data.frame(fires_final_test$id, preds$.pred_yes)

colnames(submission)[1] ="id"
colnames(submission)[2] ="intentional_cause"


view(submission)

write.csv(submission, "deliverables/submission.csv", row.names = FALSE)
```
